### ISSUE TITLE
상단 네비게이션 메뉴 hover 효과 제안

### ISSUE THREAD

**Issue by JungWinter** [dev-meetup/dev-meetup.github.io#51]
![image](https://user-images.githubusercontent.com/13811604/45369462-f4f97d00-b620-11e8-9ded-6de6cb060c95.png)

현재 해당 부분 `<a>` 태그에 `href` 속성이 없어 hover시 포인터가 변하지 않는데 이를 `<a href>`로 변경하면 더 좋아지지 않을까하여 제안드립니다.

**Comment by AhnSeongHyun** [comment]
감사합니다. 👍
